### PR TITLE
remove shapeless imports

### PR DESCRIPTION
**Pull request by yanns**
Shapeless was removed in parboiled2 upstream.
Avoid depending on it directly for an easier upgrade path.

### CODE REVIEW

**Comment by yanns** [comment]
@performantdata please check this.

**Comment by performantdata** [comment]
> Shapeless was removed in parboiled2 upstream.

I don't see why you say that. I see:
```
sangria-root> sangria-parser/dependencyTree
[info] org.sangria-graphql:sangria-parser_2.13:3.0.0-RC6+18-c326b13c-SNAPSHOT [S]
[info]   +-org.parboiled:parboiled_2.13:2.3.0 [S]
[info]   | +-com.chuusai:shapeless_2.13:2.3.4 [S]
[info]   | 
[info]   +-org.sangria-graphql:sangria-ast_2.13:3.0.0-RC6+18-c326b13c-SNAPSHOT [S]
```
Clearly some library was pulling it in for me to be able to do the import. Or are you saying that it _will be_ removed in a later version?

Either way, as long as it compiles…

**Comment by yanns** [comment]
for info: https://github.com/sirthias/parboiled2/pull/271

**Comment by performantdata** [comment]
> for info: [sirthias/parboiled2#271](https://github.com/sirthias/parboiled2/pull/271)

Huh. I'd have thought that Shapeless would have been ported to Scala 3 by now, it's so important.

**Comment by yanns** [comment]
feel free to help if you can / want: https://github.com/sirthias/parboiled2/pull/280

**Pull request merged**
